# Generated by Django 2.2.7 on 2019-12-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r2',
            field=models.ManyToManyField(blank=True, related_name='customtext_r2', to='home.HomePage'),
        ),
    ]
