# Generated by Django 2.2.7 on 2019-12-05 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_customtext_r2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r21',
            field=models.ManyToManyField(blank=True, related_name='customtext_r21', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customtext',
            name='r3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
